### ISSUE TITLE
Mind if I use the wsdl files?

### ISSUE THREAD

**Issue by Garethp** [WsdlToPhp/PackageEws365#3]
Hi

I'm looking to update my library to the latest schemas, but can't seem to find out how to grab them from Office365, and don't have my own 2013 server. Can I use the wsdl files that you have?

Thanks,
Gareth

**Comment by mikaelcom** [comment]
Of course, I don't see any problem,
By the way, if you are familiar with using this Web Service, I would be happy to have some feedback about the usage of this project, thx,

**Comment by Garethp** [comment]
I'm not using this, sorry. I found this because I remember we commented on the same issue some time ago, and I'm maintaining my own EWS library [`garethp/php-ews`](http://github.com/garethp/php-ews), and wanted to upgrade my schema soon.
