### ISSUE TITLE
do you know how to download others' manifest files?

### ISSUE THREAD

**Issue by yiyangli-okta** [WsdlToPhp/PackageEws365#4]
Hi there, 

   Thanks for the great project. This is Yiyang, from Okta. For some reasons, I am developing a web app to install/upload office add-ons, do you know how to download or fetch the manifests files. I tried the EWS operation called `getappmanifests` ([MSDN](https://msdn.microsoft.com/en-us/library/microsoft.exchange.webservices.data.exchangeservice.getappmanifests%28v=exchg.80%29.aspx))  on a user with many add-ons installed, but I could get Salesforce, Bing Maps and other 3 default apps' manifests. I can't get other great projects like Zendesk, Uber, Evernote and etc. Do you know the reasons, and do you know a site where I could download their manifests? Thanks very much. 

Yiyang

**Comment by mikaelcom** [comment]
Hi, thanks for your interest in the project, if you need any further help feel free to contact me again,
good luck,
